In [9]:
#Question 1
#Write a Python program to convert an array to an ordinary list with the same items.we can use the np.tolist() function
#################################################
#AnswerQ1#
##########
import numpy as np
a=np.array([1,2,3,4,5,6])
L=a.tolist()
print(L)

[1, 2, 3, 4, 5, 6]


In [13]:
#Question 2 
#Write a NumPy program to compute the sum of the diagonal elements of a given array.
#Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function
##################################################
#AnswerQ2#
##########
import numpy as np
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,15]])
print(a)
b=np.trace(a)
print(b)
#c=np.diagonal(a)
#print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 15]]
33


In [13]:
#Question 3
#Given an array of your choice, get all the values higher than X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 
####################################################
#AnswerQ3#
############
import numpy as np
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,15]])
print(a)
x = 2


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 15]]


In [7]:
#Question 4
#Given two arrays, A & B have the same shape. The task is to apply addition by hand: C is the new array.
#################################################
#AnswerQ4#
########
import numpy as np
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.array(A + B)
print(C)

[5 7 9]


In [12]:
#Question 5
#Write a NumPy program to subtract the mean of each row of a given matrix.Hint: use the mean function
####################################################
#AnswerQ5#
##########
import numpy as np
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,15]])
b=a - a.mean(axis=0)
print (b)

[[-6.   -6.   -6.   -5.75]
 [-2.   -2.   -2.   -1.75]
 [ 2.    2.    2.    2.25]
 [ 6.    6.    6.    5.25]]
